-- PROPOSAL ONLY — NOT A PRODUCTION MIGRATION YET.
-- Move this file into supabase/migrations/ only after it passes on an isolated
-- Supabase preview branch and the RLS/deny tests have been reviewed.
-- This proposal is additive: it does not drop, truncate, rename, or rewrite
-- existing business tables.

begin;

create schema if not exists lena authorization postgres;
comment on schema lena is
  'Private control-plane schema for Lena event intake, provenance, RAG, memory, approvals, and execution receipts.';

revoke all on schema lena from public, anon, authenticated;
grant usage on schema lena to service_role;

-- Composite tenant keys let child tables enforce organization consistency,
-- even though the public parent IDs are already globally unique.
create unique index if not exists projects_organization_id_id_uidx
  on public.projects (organization_id, id);
create unique index if not exists governance_runs_organization_id_id_uidx
  on public.governance_runs (organization_id, id);

create table if not exists lena.webhook_events (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null references public.organizations(id) on delete cascade,
  provider text not null check (provider ~ '^[a-z0-9][a-z0-9._-]{0,63}$'),
  delivery_id text,
  event_type text not null,
  occurred_at timestamptz,
  received_at timestamptz not null default now(),
  last_seen_at timestamptz not null default now(),
  idempotency_key text not null,
  source text,
  headers jsonb not null default '{}'::jsonb check (jsonb_typeof(headers) = 'object'),
  payload jsonb not null,
  status text not null default 'received'
    check (status in ('received', 'processing', 'processed', 'failed', 'dead_letter')),
  attempts integer not null default 1 check (attempts >= 1),
  last_error text,
  processed_at timestamptz,
  created_at timestamptz not null default now(),
  unique (organization_id, id),
  unique (organization_id, idempotency_key)
);

create table if not exists lena.sources (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null references public.organizations(id) on delete cascade,
  provider text not null,
  external_id text not null,
  source_type text not null,
  canonical_uri text,
  access_scope text not null default 'private'
    check (access_scope in ('private', 'organization', 'project', 'public')),
  metadata jsonb not null default '{}'::jsonb check (jsonb_typeof(metadata) = 'object'),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (organization_id, id),
  unique (organization_id, provider, external_id)
);

create table if not exists lena.source_versions (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null references public.organizations(id) on delete cascade,
  source_id uuid not null,
  source_hash text not null check (length(source_hash) between 32 and 128),
  revision text,
  mime_type text,
  language text not null default 'und',
  author text,
  observed_at timestamptz not null default now(),
  valid_from timestamptz,
  valid_to timestamptz,
  supersedes_id uuid,
  raw_storage_path text,
  metadata jsonb not null default '{}'::jsonb check (jsonb_typeof(metadata) = 'object'),
  created_at timestamptz not null default now(),
  check (valid_to is null or valid_from is null or valid_to >= valid_from),
  foreign key (organization_id, source_id)
    references lena.sources(organization_id, id) on delete cascade,
  foreign key (organization_id, supersedes_id)
    references lena.source_versions(organization_id, id)
    on delete set null (supersedes_id),
  unique (organization_id, id),
  unique (source_id, source_hash)
);

create table if not exists lena.documents (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null references public.organizations(id) on delete cascade,
  project_id uuid,
  source_version_id uuid not null,
  external_document_id text,
  title text not null,
  canonical_text text not null,
  revision text,
  language text not null default 'und',
  author text,
  occurred_at timestamptz,
  metadata jsonb not null default '{}'::jsonb check (jsonb_typeof(metadata) = 'object'),
  search_vector tsvector generated always as (
    setweight(to_tsvector('simple', coalesce(title, '')), 'A') ||
    setweight(to_tsvector('simple', coalesce(canonical_text, '')), 'B')
  ) stored,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  foreign key (organization_id, project_id)
    references public.projects(organization_id, id)
    on delete set null (project_id),
  foreign key (organization_id, source_version_id)
    references lena.source_versions(organization_id, id) on delete restrict,
  unique (organization_id, id),
  unique (source_version_id, external_document_id)
);

create table if not exists lena.chunks (
  id bigint generated by default as identity primary key,
  organization_id uuid not null references public.organizations(id) on delete cascade,
  document_id uuid not null,
  chunk_index integer not null check (chunk_index >= 0),
  content text not null,
  token_count integer check (token_count is null or token_count >= 0),
  locator jsonb not null default '{}'::jsonb check (jsonb_typeof(locator) = 'object'),
  metadata jsonb not null default '{}'::jsonb check (jsonb_typeof(metadata) = 'object'),
  search_vector tsvector generated always as (
    to_tsvector('simple', coalesce(content, ''))
  ) stored,
  created_at timestamptz not null default now(),
  foreign key (organization_id, document_id)
    references lena.documents(organization_id, id) on delete cascade,
  unique (organization_id, id),
  unique (document_id, chunk_index)
);

create table if not exists lena.embedding_profiles (
  id uuid primary key default gen_random_uuid(),
  name text not null unique,
  provider text not null,
  model text not null,
  dimensions integer not null check (dimensions between 1 and 2000),
  distance_metric text not null default 'cosine'
    check (distance_metric in ('cosine', 'l2', 'inner_product')),
  normalized boolean not null default false,
  active boolean not null default true,
  metadata jsonb not null default '{}'::jsonb check (jsonb_typeof(metadata) = 'object'),
  created_at timestamptz not null default now(),
  unique (id, dimensions),
  unique (provider, model, dimensions)
);

create table if not exists lena.chunk_embeddings (
  organization_id uuid not null references public.organizations(id) on delete cascade,
  chunk_id bigint not null,
  embedding_profile_id uuid not null,
  dimensions integer not null,
  embedding extensions.vector not null,
  created_at timestamptz not null default now(),
  primary key (chunk_id, embedding_profile_id),
  foreign key (organization_id, chunk_id)
    references lena.chunks(organization_id, id) on delete cascade,
  foreign key (embedding_profile_id, dimensions)
    references lena.embedding_profiles(id, dimensions) on delete restrict,
  check (extensions.vector_dims(embedding) = dimensions)
);

create table if not exists lena.claims (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null references public.organizations(id) on delete cascade,
  project_id uuid,
  claim_hash text not null,
  subject text not null,
  predicate text not null,
  object_text text,
  object_data jsonb,
  confidence numeric(5,4) not null default 0.5000
    check (confidence between 0 and 1),
  status text not null default 'candidate'
    check (status in ('candidate', 'validated', 'rejected', 'superseded', 'disputed')),
  observed_at timestamptz not null default now(),
  valid_from timestamptz,
  valid_to timestamptz,
  supersedes_id uuid,
  metadata jsonb not null default '{}'::jsonb check (jsonb_typeof(metadata) = 'object'),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (valid_to is null or valid_from is null or valid_to >= valid_from),
  foreign key (organization_id, project_id)
    references public.projects(organization_id, id)
    on delete set null (project_id),
  foreign key (organization_id, supersedes_id)
    references lena.claims(organization_id, id)
    on delete set null (supersedes_id),
  unique (organization_id, id),
  unique (organization_id, claim_hash)
);

create table if not exists lena.claim_evidence (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null references public.organizations(id) on delete cascade,
  claim_id uuid not null,
  document_id uuid not null,
  chunk_id bigint,
  evidence_role text not null default 'support'
    check (evidence_role in ('support', 'contradict', 'context')),
  quote_text text,
  locator jsonb not null default '{}'::jsonb check (jsonb_typeof(locator) = 'object'),
  created_at timestamptz not null default now(),
  foreign key (organization_id, claim_id)
    references lena.claims(organization_id, id) on delete cascade,
  foreign key (organization_id, document_id)
    references lena.documents(organization_id, id) on delete cascade,
  foreign key (organization_id, chunk_id)
    references lena.chunks(organization_id, id) on delete cascade,
  unique (organization_id, id)
);

create unique index if not exists claim_evidence_dedupe_idx
  on lena.claim_evidence (
    claim_id,
    document_id,
    coalesce(chunk_id, 0),
    evidence_role
  );

create table if not exists lena.memory_items (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null references public.organizations(id) on delete cascade,
  project_id uuid,
  memory_type text not null,
  memory_key text not null,
  value jsonb not null,
  confidence numeric(5,4) not null default 0.5000
    check (confidence between 0 and 1),
  state text not null default 'candidate'
    check (state in ('candidate', 'validated', 'rejected', 'superseded', 'expired')),
  source_claim_id uuid,
  validated_by uuid references auth.users(id) on delete set null,
  validated_at timestamptz,
  valid_from timestamptz,
  valid_to timestamptz,
  review_due_at timestamptz,
  supersedes_id uuid,
  metadata jsonb not null default '{}'::jsonb check (jsonb_typeof(metadata) = 'object'),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (valid_to is null or valid_from is null or valid_to >= valid_from),
  foreign key (organization_id, project_id)
    references public.projects(organization_id, id) on delete cascade,
  foreign key (organization_id, source_claim_id)
    references lena.claims(organization_id, id)
    on delete set null (source_claim_id),
  foreign key (organization_id, supersedes_id)
    references lena.memory_items(organization_id, id)
    on delete set null (supersedes_id),
  unique (organization_id, id)
);

create unique index if not exists memory_items_one_validated_key_idx
  on lena.memory_items (organization_id, coalesce(project_id, '00000000-0000-0000-0000-000000000000'::uuid), memory_type, memory_key)
  where state = 'validated';

create table if not exists lena.approvals (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null references public.organizations(id) on delete cascade,
  run_id uuid,
  action_type text not null,
  target text not null,
  requested_payload_hash text not null,
  status text not null default 'pending'
    check (status in ('pending', 'approved', 'rejected', 'expired', 'revoked')),
  requested_at timestamptz not null default now(),
  expires_at timestamptz,
  decided_at timestamptz,
  decided_by uuid references auth.users(id) on delete set null,
  rationale text,
  metadata jsonb not null default '{}'::jsonb check (jsonb_typeof(metadata) = 'object'),
  foreign key (organization_id, run_id)
    references public.governance_runs(organization_id, id) on delete cascade,
  unique (organization_id, id)
);

create table if not exists lena.execution_receipts (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null references public.organizations(id) on delete cascade,
  run_id uuid,
  event_id uuid,
  approval_id uuid,
  action_type text not null,
  target text not null,
  requested_model text,
  actual_model text,
  status text not null
    check (status in ('started', 'succeeded', 'failed', 'rolled_back', 'cancelled')),
  input_hash text,
  output_hash text,
  tests jsonb not null default '[]'::jsonb check (jsonb_typeof(tests) = 'array'),
  artifacts jsonb not null default '[]'::jsonb check (jsonb_typeof(artifacts) = 'array'),
  metrics jsonb not null default '{}'::jsonb check (jsonb_typeof(metrics) = 'object'),
  error text,
  started_at timestamptz not null default now(),
  finished_at timestamptz,
  created_at timestamptz not null default now(),
  foreign key (organization_id, run_id)
    references public.governance_runs(organization_id, id) on delete cascade,
  foreign key (organization_id, event_id)
    references lena.webhook_events(organization_id, id)
    on delete set null (event_id),
  foreign key (organization_id, approval_id)
    references lena.approvals(organization_id, id)
    on delete set null (approval_id),
  unique (organization_id, id)
);

create index if not exists webhook_events_status_received_idx
  on lena.webhook_events (organization_id, status, received_at);
create index if not exists webhook_events_provider_delivery_idx
  on lena.webhook_events (provider, delivery_id) where delivery_id is not null;
create index if not exists source_versions_source_observed_idx
  on lena.source_versions (source_id, observed_at desc);
create index if not exists documents_org_project_occurred_idx
  on lena.documents (organization_id, project_id, occurred_at desc);
create index if not exists documents_search_idx
  on lena.documents using gin (search_vector);
create index if not exists chunks_org_document_idx
  on lena.chunks (organization_id, document_id, chunk_index);
create index if not exists chunks_search_idx
  on lena.chunks using gin (search_vector);
create index if not exists chunk_embeddings_profile_idx
  on lena.chunk_embeddings (embedding_profile_id, chunk_id);
create index if not exists claims_org_project_status_idx
  on lena.claims (organization_id, project_id, status, observed_at desc);
create index if not exists claim_evidence_claim_idx
  on lena.claim_evidence (claim_id);
create index if not exists claim_evidence_chunk_idx
  on lena.claim_evidence (chunk_id) where chunk_id is not null;
create index if not exists memory_items_review_idx
  on lena.memory_items (organization_id, state, review_due_at)
  where review_due_at is not null;
create index if not exists approvals_run_status_idx
  on lena.approvals (run_id, status, requested_at desc);
create index if not exists execution_receipts_run_idx
  on lena.execution_receipts (run_id, started_at desc);

alter table lena.webhook_events enable row level security;
alter table lena.sources enable row level security;
alter table lena.source_versions enable row level security;
alter table lena.documents enable row level security;
alter table lena.chunks enable row level security;
alter table lena.embedding_profiles enable row level security;
alter table lena.chunk_embeddings enable row level security;
alter table lena.claims enable row level security;
alter table lena.claim_evidence enable row level security;
alter table lena.memory_items enable row level security;
alter table lena.approvals enable row level security;
alter table lena.execution_receipts enable row level security;

revoke all on all tables in schema lena from public, anon, authenticated;
revoke all on all sequences in schema lena from public, anon, authenticated;
grant select, insert, update, delete on all tables in schema lena to service_role;
grant usage, select on all sequences in schema lena to service_role;

alter default privileges for role postgres in schema lena
  revoke all on tables from public, anon, authenticated;
alter default privileges for role postgres in schema lena
  revoke all on sequences from public, anon, authenticated;
alter default privileges for role postgres in schema lena
  grant select, insert, update, delete on tables to service_role;
alter default privileges for role postgres in schema lena
  grant usage, select on sequences to service_role;

create or replace function public.ingest_lena_event(p_event jsonb)
returns jsonb
language plpgsql
security definer
set search_path = pg_catalog
as $$
declare
  v_organization_id uuid;
  v_provider text;
  v_delivery_id text;
  v_event_type text;
  v_occurred_at timestamptz;
  v_received_at timestamptz;
  v_idempotency_key text;
  v_source text;
  v_headers jsonb;
  v_payload jsonb;
  v_event_id uuid;
  v_inserted boolean;
begin
  if p_event is null or jsonb_typeof(p_event) <> 'object' then
    raise exception using errcode = '22023', message = 'p_event must be a JSON object';
  end if;

  v_organization_id := nullif(btrim(p_event ->> 'organization_id'), '')::uuid;
  v_provider := lower(nullif(btrim(p_event ->> 'provider'), ''));
  v_delivery_id := nullif(btrim(p_event ->> 'delivery_id'), '');
  v_event_type := nullif(btrim(p_event ->> 'event_type'), '');
  v_occurred_at := nullif(btrim(p_event ->> 'occurred_at'), '')::timestamptz;
  v_received_at := coalesce(
    nullif(btrim(p_event ->> 'received_at'), '')::timestamptz,
    now()
  );
  v_idempotency_key := nullif(btrim(p_event ->> 'idempotency_key'), '');
  v_source := nullif(btrim(p_event ->> 'source'), '');
  v_headers := coalesce(p_event -> 'headers', '{}'::jsonb);
  v_payload := coalesce(p_event -> 'payload', 'null'::jsonb);

  if v_organization_id is null
     or v_provider is null
     or v_event_type is null
     or v_idempotency_key is null then
    raise exception using
      errcode = '22023',
      message = 'organization_id, provider, event_type, and idempotency_key are required';
  end if;

  if jsonb_typeof(v_headers) <> 'object' then
    raise exception using errcode = '22023', message = 'headers must be a JSON object';
  end if;

  insert into lena.webhook_events (
    organization_id,
    provider,
    delivery_id,
    event_type,
    occurred_at,
    received_at,
    last_seen_at,
    idempotency_key,
    source,
    headers,
    payload
  ) values (
    v_organization_id,
    v_provider,
    v_delivery_id,
    v_event_type,
    v_occurred_at,
    v_received_at,
    v_received_at,
    v_idempotency_key,
    v_source,
    v_headers,
    v_payload
  )
  on conflict (organization_id, idempotency_key) do nothing
  returning id into v_event_id;

  v_inserted := found;

  if not v_inserted then
    update lena.webhook_events
       set attempts = attempts + 1,
           last_seen_at = greatest(last_seen_at, v_received_at)
     where organization_id = v_organization_id
       and idempotency_key = v_idempotency_key
     returning id into v_event_id;
  end if;

  return jsonb_build_object(
    'event_id', v_event_id,
    'status', case when v_inserted then 'inserted' else 'duplicate' end
  );
end;
$$;

alter function public.ingest_lena_event(jsonb) owner to postgres;
revoke all on function public.ingest_lena_event(jsonb) from public, anon, authenticated;
grant execute on function public.ingest_lena_event(jsonb) to service_role;

comment on function public.ingest_lena_event(jsonb) is
  'Idempotent server-only ingress for verified webhook envelopes. Call with a Supabase secret key; never expose that key to a browser.';

commit;
